### PR TITLE
Budget Capstone Project

### PR DESCRIPTION
**Pull request by hansderly**
In this pull request, i completed the following activities for the Microverse budget-app project:

- Set up the repository and tools.
- Create your models according to the ERD diagram.
- Add validations and tests.
- Implement the authentication and authorization.
- Create the page to add a category.
- Create the home page.
- Create the page to add an expense.
- Create the expenses page.
- Make sure tests are still passing.
- Deploy the project
- Record a video of the project.
- Add README and a pull request for review.

### CODE REVIEW

**Review by BenMukebo — COMMENTED** [review]
## STATUS: INVALID ❌ 

Hi  @hansderly,

I can't miss felicitating your efforts and energy, you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project, that did not follow the GitHub flow.
- Since this is a solo Capston Project, The Pull Request should be made from the “feature branch” into the `dev` branch and not the "dev" to the "main". I suggest you change this. 👍🏻 

### To improve ⏫ 



Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@BenMukebo) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit.

**Comment by hansderly** [comment]
Hi @BenMukebo 
The requirement for the project state that we should use the [GitFLow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=What%20is%20Gitflow%3F,lived%20branches%20and%20larger%20commits.)
Where each feature reside in a feature branch before mergin to dev branch
and when you ready to deploy you made a pull request to the main branch

**Comment by hansderly** [comment]
@BenMukebo can you please take a look?
Screenshot 2023-06-03 114028

**Comment by BenMukebo** [comment]
Hello @hansderly As I explain you in the call this is how you need to use gitflow when it's  a sole capston app. but if you need more explaination you may request for a second opinion so that senior CR will give you more explaination!!

**Review by Whoistolu — COMMENTED** [review]
Hi @hansderly 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that does not follow the correct git-flow. Kindly ensure your PR is opened from a feature branch wanting to merge into the development branch in order to have the correct git-flow.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
